import { runGuardrailRegressionTests } from '../lib/agent-v2/guardrailEvaluation.js';
import './reliability.js';
import './commerceSecurity.js';
import './orchestratorWiring.js';
import './adversarialDecisions.js';
import './completionEvidence.js';
import './agentLoopRecovery.js';
import './goalEvaluation.js';
import './ciSmoke.js';
import { runIntegrationScenarios } from './integration.js';
const guardrails = runGuardrailRegressionTests();
console.log('Kavi V2 guardrail tests:', guardrails);
const integration = await runIntegrationScenarios();
console.log('Kavi V2 integration tests:', integration);
console.log('Kavi V2 security/reliability suites: PASS');
